package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF0061A4)
val Background = Color(0xFFFDFBFF)
val Surface = Color(0xFFFDFBFF)
val SurfaceDim = Color(0xFFE1E2EC)
val SurfaceBright = Color(0xFFFDFBFF)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF3F4F9)
val SurfaceContainer = Color(0xFFE1E2EC)
val SurfaceContainerHigh = Color(0xFFD1E4FF)
val SurfaceContainerHighest = Color(0xFFE1E2EC)
val OnSurface = Color(0xFF1A1C1E)
val OnSurfaceVariant = Color(0xFF43474E)
val InverseSurface = Color(0xFF1A1C1E)
val InverseOnSurface = Color(0xFFFDFBFF)
val Outline = Color(0xFFE1E2EC)
val OutlineVariant = Color(0xFFE1E2EC)
val SurfaceTint = Color(0xFF0061A4)
val PrimaryContainer = Color(0xFFD1E4FF)
val OnPrimaryContainer = Color(0xFF001D36)
val InversePrimary = Color(0xFF0061A4)
val Secondary = Color(0xFF43474E)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFE1E2EC)
val OnSecondaryContainer = Color(0xFF1A1C1E)
val Tertiary = Color(0xFF2E6B12)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFD1E4FF)
val OnTertiaryContainer = Color(0xFF001D36)
val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)
