package com.example

object LanguageManager {
    fun getString(key: String, lang: String): String {
        val dictionary = if (lang == "es") esStrings else enStrings
        return dictionary[key] ?: key
    }

    private val esStrings = mapOf(
        "nav_library" to "Biblioteca",
        "nav_player" to "Reproductor",
        "nav_stats" to "Estadísticas",
        "nav_settings" to "Ajustes",
        "sys_config" to "Configuración del Sistema",
        "settings_title" to "Ajustes",
        "permissions" to "Permisos",
        "local_storage" to "Acceso a Almacenamiento",
        "local_storage_desc" to "Requerido para indexar libros y reproducirlos sin conexión.",
        "bg_playback" to "Reproducción en Segundo Plano",
        "bg_playback_desc" to "Continúa el audio cuando la pantalla está bloqueada o en segundo plano.",
        "sync_frequency" to "Frecuencia de Guardado",
        "sync_freq_desc" to "SELECCIONAR INTERVALO DE AUTOGUARDADO",
        "sync_manual" to "Manual",
        "scan_dirs" to "Directorios de Escaneo",
        "add_dir" to "+ Añadir Directorio",
        "no_dirs" to "No hay directorios de escaneo configurados.",
        "diagnostics" to "Diagnósticos del Motor de Audio",
        "latency" to "Latencia de DB",
        "buffer" to "Salud del Buffer",
        "cache" to "Uso de Caché",
        "rebuild_db" to "Reconstruir base de datos",
        "rebuild_desc" to "Borrar y volver a escanear todos los audiolibros",
        // Stats strings
        "stats_today_prog" to "Progreso de Hoy",
        "stats_meta_desc" to "Meta diaria recomendada: 60 minutos",
        "stats_completed" to "¡Asombroso! Meta cumplida hoy 🎉",
        "stats_half" to "¡Más de la mitad! Estás muy cerca",
        "stats_momentum" to "Mantén el impulso, vas muy bien",
        "stats_start" to "Empieza a reproducir un libro para activar tu día",
        "stats_curr_streak" to "Racha Actual",
        "stats_max_streak" to "Racha Máxima",
        "stats_rec_hours" to "Récord personal",
        "stats_fuego" to "¡Racha de fuego!",
        "stats_inicia" to "¡Inicia hoy!",
        "stats_weekly" to "Historial Semanal",
        "stats_total" to "Total",
        "stats_rank" to "Rango",
        "stats_next_rank" to "Siguiente rango",
        "stats_tester" to "Pruebas de Estadísticas (Simulador)",
        "stats_tester_desc" to "Añade o resta tiempo manualmente para corroborar cómo responde el gráfico, las metas diarias, aumentan tus rachas y suben los rangos al instante.",
        "stats_minutes_add" to "+15 min",
        "stats_minutes_sub" to "-15 min",
        "stats_clear" to "Borrar e iniciar de 0",
        // Language & theming strings
        "lang_section" to "Idioma / Language",
        "lang_label" to "Seleccionar Idioma",
        "theme_section" to "Personalización y Tema",
        "theme_mode_label" to "Modo de Tema",
        "theme_dark" to "Oscuro",
        "theme_light" to "Claro",
        "theme_peach" to "Melocotón Atardecer",
        "theme_ocean" to "Abismo Marino",
        "theme_emerald" to "Verde Místico",
        "theme_cosmic" to "Pizarra Cósmica",
        "theme_custom" to "Personalizado (Tú Eliges)",
        "theme_custom_title" to "Creador de Tema Propio",
        "theme_primary_color" to "Color Primario",
        "theme_bg_color" to "Color de Fondo",
        "theme_secondary_color" to "Color Secundario",
        "theme_palette_pre" to "Paletas de Colores de Autor",
        "theme_reset" to "Restaurar por defecto",
        "theme_unlocked" to "Disfruta de tu diseño unico e irrepetible!"
    )

    private val enStrings = mapOf(
        "nav_library" to "Library",
        "nav_player" to "Player",
        "nav_stats" to "Statistics",
        "nav_settings" to "Settings",
        "sys_config" to "System Configuration",
        "settings_title" to "Settings",
        "permissions" to "Permissions",
        "local_storage" to "Local Storage Access",
        "local_storage_desc" to "Required for library indexing and offline playback.",
        "bg_playback" to "Background Playback",
        "bg_playback_desc" to "Continue audio when the screen is locked or in background.",
        "sync_frequency" to "Auto-save Frequency",
        "sync_freq_desc" to "SELECT LISTENING PROGRESS SYNC INTERVAL",
        "sync_manual" to "Manual",
        "scan_dirs" to "Scan Directories",
        "add_dir" to "+ Add Directory",
        "no_dirs" to "No scan directories configured.",
        "diagnostics" to "Audio Engine Diagnostics",
        "latency" to "DB Latency",
        "buffer" to "Buffer Health",
        "cache" to "Cache Usage",
        "rebuild_db" to "Rebuild database",
        "rebuild_desc" to "Completely rescan and index library",
        // Stats strings
        "stats_today_prog" to "Today's Progress",
        "stats_meta_desc" to "Recommended daily goal: 60 minutes",
        "stats_completed" to "Amazing! Daily goal achieved today 🎉",
        "stats_half" to "More than halfway there! Keep it up!",
        "stats_momentum" to "Keep the momentum going, doing great!",
        "stats_start" to "Play an audiobook to kick off your day!",
        "stats_curr_streak" to "Current Streak",
        "stats_max_streak" to "Max Streak",
        "stats_rec_hours" to "Personal record",
        "stats_fuego" to "On fire!",
        "stats_inicia" to "Start today!",
        "stats_weekly" to "Weekly History",
        "stats_total" to "Total",
        "stats_rank" to "Rank",
        "stats_next_rank" to "Next rank",
        "stats_tester" to "Stats Simulator (Testing)",
        "stats_tester_desc" to "Manually adjust values to test real-time updates of streaks, graphs, ranks, and daily progress feedback.",
        "stats_minutes_add" to "+15 min",
        "stats_minutes_sub" to "-15 min",
        "stats_clear" to "Reset stats to zero",
        // Language & theming strings
        "lang_section" to "Language / Idioma",
        "lang_label" to "Select Language",
        "theme_section" to "Theme & Customization",
        "theme_mode_label" to "Theme Mode",
        "theme_dark" to "Dark Mode",
        "theme_light" to "Light Mode",
        "theme_peach" to "Peach Sunset",
        "theme_ocean" to "Abyss Marine",
        "theme_emerald" to "Sage Mystic",
        "theme_cosmic" to "Cosmic Slate",
        "theme_custom" to "Custom (Handcrafted)",
        "theme_custom_title" to "Custom Palette Maker",
        "theme_primary_color" to "Primary Color",
        "theme_bg_color" to "Background Color",
        "theme_secondary_color" to "Secondary Color",
        "theme_palette_pre" to "Designer Palettes",
        "theme_reset" to "Reset Theme",
        "theme_unlocked" to "Enjoy your bespoke dynamic interface!"
    )
}
