package com.example

object LanguageManager {
    fun getString(key: String, lang: String): String {
        val dictionary = if (lang == "es") esStrings else enStrings
        return dictionary[key] ?: key
    }

    private val esStrings = mapOf(
        "nav_library" to "Biblioteca",
        "nav_player" to "Reproductor",
        "nav_stats" to "Estadísticas",
        "nav_settings" to "Ajustes",
        "sys_config" to "Configuración del Sistema",
        "settings_title" to "Ajustes",
        "permissions" to "Permisos",
        "local_storage" to "Acceso a Almacenamiento",
        "local_storage_desc" to "Requerido para indexar libros y reproducirlos sin conexión.",
        "bg_playback" to "Reproducción en Segundo Plano",
        "bg_playback_desc" to "Continúa el audio cuando la pantalla está bloqueada o en segundo plano.",
        "sync_frequency" to "Frecuencia de Guardado",
        "sync_freq_desc" to "SELECCIONAR INTERVALO DE AUTOGUARDADO",
        "sync_manual" to "Manual",
        "scan_dirs" to "Directorios de Escaneo",
        "add_dir" to "+ Añadir Directorio",
        "no_dirs" to "No hay directorios de escaneo configurados.",
        "diagnostics" to "Diagnósticos del Motor de Audio",
        "latency" to "Latencia de DB",
        "buffer" to "Salud del Buffer",
        "cache" to "Uso de Caché",
        "rebuild_db" to "Reconstruir base de datos",
        "rebuild_desc" to "Borrar y volver a escanear todos los audiolibros",
        // Stats strings
        "stats_today_prog" to "Progreso de Hoy",
        "stats_meta_desc" to "Meta diaria recomendada: 60 minutos",
        "stats_completed" to "¡Asombroso! Meta cumplida hoy 🎉",
        "stats_half" to "¡Más de la mitad! Estás muy cerca",
        "stats_momentum" to "Mantén el impulso, vas muy bien",
        "stats_start" to "Empieza a reproducir un libro para activar tu día",
        "stats_curr_streak" to "Racha Actual",
        "stats_max_streak" to "Racha Máxima",
        "stats_rec_hours" to "Récord personal",
        "stats_fuego" to "¡Racha de fuego!",
        "stats_inicia" to "¡Inicia hoy!",
        "stats_weekly" to "Historial Semanal",
        "stats_total" to "Total",
        "stats_rank" to "Rango",
        "stats_next_rank" to "Siguiente rango",
        "stats_tester" to "Pruebas de Estadísticas (Simulador)",
        "stats_tester_desc" to "Añade o resta tiempo manualmente para corroborar cómo responde el gráfico, las metas diarias, aumentan tus rachas y suben los rangos al instante.",
        "stats_minutes_add" to "+15 min",
        "stats_minutes_sub" to "-15 min",
        "stats_clear" to "Borrar e iniciar de 0",
        // Language & theming strings
        "lang_section" to "Idioma / Language",
        "lang_label" to "Seleccionar Idioma",
        "theme_section" to "Personalización y Tema",
        "theme_mode_label" to "Modo de Tema",
        "theme_dark" to "Oscuro",
        "theme_light" to "Claro",
        "theme_peach" to "Melocotón Atardecer",
        "theme_ocean" to "Abismo Marino",
        "theme_emerald" to "Verde Místico",
        "theme_cosmic" to "Pizarra Cósmica",
        "theme_custom" to "Personalizado (Tú Eliges)",
        "theme_custom_title" to "Creador de Tema Propio",
        "theme_primary_color" to "Color Primario",
        "theme_bg_color" to "Color de Fondo",
        "theme_secondary_color" to "Color Secundario",
        "theme_palette_pre" to "Paletas de Colores de Autor",
        "theme_reset" to "Restaurar por defecto",
        "theme_unlocked" to "Disfruta de tu diseño unico e irrepetible!",
        "nav_quotes" to "Frases",
        "quotes_title" to "Frases Guardadas",
        "quotes_add" to "Guardar Frase",
        "quotes_empty" to "Aún no tienes frases anotadas. ¡Añade una desde tus libros o aquí mismo!",
        "quotes_delete" to "Borrar",
        "delete_book" to "Borrar Libro",
        "delete_book_confirm" to "¿Estás seguro de que quieres borrar este libro de la biblioteca?",
        "view_mode_grid" to "Vista Cuadrícula",
        "view_mode_folder" to "Vista Carpetas",
        "quote_hint" to "Escribe una frase inspiradora...",
        "page_hint" to "Página / Capítulo (opcional)",
        "auto_scroll" to "Scroll Automático",
        "scroll_speed" to "Velocidad de Desplazamiento",
        "scroll_novel_preset" to "📖 Texto / Novela",
        "scroll_normal_preset" to "📄 Lectura Normal",
        "scroll_manga_preset" to "⚡ Manga / Cómic",
        "scroll_manga_fast_preset" to "🚀 Manga Rápido",
        "scroll_skim_preset" to "⏩ Exploración Rápida",
        // Nuevas cadenas para Estadísticas Mejoradas
        "stats_title" to "Estadísticas de Lectura",
        "stats_subtitle" to "Tu viaje de conocimiento y hábitos diarios",
        "stats_tab_overview" to "Resumen",
        "stats_tab_habits" to "Hábitos y Gráficos",
        "stats_tab_achievements" to "Logros",
        "stats_library_dist" to "Distribución por Formato",
        "stats_audio_format" to "Audiolibros",
        "stats_epub_format" to "Libros EPUB",
        "stats_pdf_format" to "PDF & Manga",
        "stats_heatmap_title" to "Matriz de Constancia (Últimos 28 días)",
        "stats_best_day" to "Día Récord",
        "stats_avg_daily" to "Promedio Diario",
        "stats_books_completed" to "Completados",
        "stats_in_progress" to "En Progreso",
        "stats_quotes_saved" to "Citas Guardadas",
        "stats_milestones_title" to "Insignias y Desafíos",
        "stats_badge_first_step" to "Primeros Pasos",
        "stats_badge_first_step_desc" to "Inicia tu primer libro en Audire",
        "stats_badge_streak_3" to "Hábito Formado",
        "stats_badge_streak_3_desc" to "Alcanza 3 días seguidos de racha",
        "stats_badge_streak_7" to "Fuego Imparable",
        "stats_badge_streak_7_desc" to "Mantén una racha de 7 días consecutivos",
        "stats_badge_hours_5" to "Maratón de Conocimiento",
        "stats_badge_hours_5_desc" to "Supera 5 horas de lectura o escucha",
        "stats_badge_collector" to "Coleccionista de Frases",
        "stats_badge_collector_desc" to "Guarda 3 o más citas memorables",
        "stats_badge_master" to "Maestro de Audire",
        "stats_badge_master_desc" to "Alcanza el rango supremo con más de 15 horas",
        // Categorías de Logros
        "achievements_all" to "Todos",
        "achievements_streaks" to "Rachas",
        "achievements_time" to "Tiempo",
        "achievements_library" to "Biblioteca",
        "achievements_quotes" to "Frases",
        "achievements_habits" to "Hábitos",
        "achievements_mastery" to "Maestría",
        "achievements_unlocked_count" to "Desbloqueados",
        // Dock del Lector y Hojas de Ajustes
        "dock_nav" to "Páginas",
        "dock_appearance" to "Apariencia",
        "dock_scroll" to "Auto-Scroll",
        "dock_quotes" to "Frases",
        "dock_voice" to "Narrador",
        "dock_pages_title" to "Navegación de Páginas",
        "dock_appearance_title" to "Ajustes de Apariencia",
        "dock_scroll_title" to "Scroll Continuo Automático",
        "dock_quotes_title" to "Frases del Libro",
        "dock_voice_title" to "Narración por Voz (TTS)",
        "dock_text_mode" to "Modo Extracción de Texto",
        "dock_visual_mode" to "Modo Hoja Original",
        "dock_inverted_night" to "Modo Noche Invertido",
        "dock_inverted_night_desc" to "Invierte colores en PDFs y mangas para proteger tu vista",
        "dock_font_size" to "Tamaño de Fuente",
        "dock_reading_theme" to "Tema de Lectura",
        "dock_add_quote_hint" to "Escribe o pega una frase destacada de esta página...",
        "dock_save_quote" to "Guardar Frase",
        "dock_jump_page" to "Saltar a Página",
        "dock_current_page" to "Página Actual",
        // Nuevas cadenas para Ajustes Modernizados
        "settings_subtitle" to "Personaliza tu experiencia auditiva y visual",
        "settings_cat_storage" to "Almacenamiento y Biblioteca",
        "settings_cat_appearance" to "Apariencia y Tema",
        "settings_cat_playback" to "Reproducción y Voz TTS",
        "settings_cat_data" to "Respaldo y Diagnóstico",
        "settings_cat_danger" to "Mantenimiento y Zona Crítica",
        "settings_rescan_btn" to "Escanear Archivos Ahora",
        "settings_rescan_desc" to "Indexar nuevos audiolibros, epubs y pdfs detectados"
    )

    private val enStrings = mapOf(
        "nav_library" to "Library",
        "nav_player" to "Player",
        "nav_stats" to "Statistics",
        "nav_settings" to "Settings",
        "sys_config" to "System Configuration",
        "settings_title" to "Settings",
        "permissions" to "Permissions",
        "local_storage" to "Local Storage Access",
        "local_storage_desc" to "Required for library indexing and offline playback.",
        "bg_playback" to "Background Playback",
        "bg_playback_desc" to "Continue audio when the screen is locked or in background.",
        "sync_frequency" to "Auto-save Frequency",
        "sync_freq_desc" to "SELECT LISTENING PROGRESS SYNC INTERVAL",
        "sync_manual" to "Manual",
        "scan_dirs" to "Scan Directories",
        "add_dir" to "+ Add Directory",
        "no_dirs" to "No scan directories configured.",
        "diagnostics" to "Audio Engine Diagnostics",
        "latency" to "DB Latency",
        "buffer" to "Buffer Health",
        "cache" to "Cache Usage",
        "rebuild_db" to "Rebuild database",
        "rebuild_desc" to "Completely rescan and index library",
        // Stats strings
        "stats_today_prog" to "Today's Progress",
        "stats_meta_desc" to "Recommended daily goal: 60 minutes",
        "stats_completed" to "Amazing! Daily goal achieved today 🎉",
        "stats_half" to "More than halfway there! Keep it up!",
        "stats_momentum" to "Keep the momentum going, doing great!",
        "stats_start" to "Play an audiobook to kick off your day!",
        "stats_curr_streak" to "Current Streak",
        "stats_max_streak" to "Max Streak",
        "stats_rec_hours" to "Personal record",
        "stats_fuego" to "On fire!",
        "stats_inicia" to "Start today!",
        "stats_weekly" to "Weekly History",
        "stats_total" to "Total",
        "stats_rank" to "Rank",
        "stats_next_rank" to "Next rank",
        "stats_tester" to "Stats Simulator (Testing)",
        "stats_tester_desc" to "Manually adjust values to test real-time updates of streaks, graphs, ranks, and daily progress feedback.",
        "stats_minutes_add" to "+15 min",
        "stats_minutes_sub" to "-15 min",
        "stats_clear" to "Reset stats to zero",
        // Language & theming strings
        "lang_section" to "Language / Idioma",
        "lang_label" to "Select Language",
        "theme_section" to "Theme & Customization",
        "theme_mode_label" to "Theme Mode",
        "theme_dark" to "Dark Mode",
        "theme_light" to "Light Mode",
        "theme_peach" to "Peach Sunset",
        "theme_ocean" to "Abyss Marine",
        "theme_emerald" to "Sage Mystic",
        "theme_cosmic" to "Cosmic Slate",
        "theme_custom" to "Custom (Handcrafted)",
        "theme_custom_title" to "Custom Palette Maker",
        "theme_primary_color" to "Primary Color",
        "theme_bg_color" to "Background Color",
        "theme_secondary_color" to "Secondary Color",
        "theme_palette_pre" to "Designer Palettes",
        "theme_reset" to "Reset Theme",
        "theme_unlocked" to "Enjoy your bespoke dynamic interface!",
        "nav_quotes" to "Quotes",
        "quotes_title" to "Saved Quotes",
        "quotes_add" to "Save Quote",
        "quotes_empty" to "No quotes saved yet. Add one from your books or right here!",
        "quotes_delete" to "Delete",
        "delete_book" to "Delete Book",
        "delete_book_confirm" to "Are you sure you want to delete this book from your library?",
        "view_mode_grid" to "Grid View",
        "view_mode_folder" to "Folder View",
        "quote_hint" to "Write an inspiring phrase...",
        "page_hint" to "Page / Chapter (optional)",
        "auto_scroll" to "Auto-Scroll",
        "scroll_speed" to "Scroll Speed",
        "scroll_novel_preset" to "📖 Text / Novel",
        "scroll_normal_preset" to "📄 Normal Reading",
        "scroll_manga_preset" to "⚡ Manga / Comic",
        "scroll_manga_fast_preset" to "🚀 Fast Manga",
        "scroll_skim_preset" to "⏩ Quick Skim",
        // New strings for Enhanced Stats
        "stats_title" to "Reading Statistics",
        "stats_subtitle" to "Your learning journey and daily habits",
        "stats_tab_overview" to "Overview",
        "stats_tab_habits" to "Habits & Charts",
        "stats_tab_achievements" to "Achievements",
        "stats_library_dist" to "Format Distribution",
        "stats_audio_format" to "Audiobooks",
        "stats_epub_format" to "EPUB Books",
        "stats_pdf_format" to "PDF & Manga",
        "stats_heatmap_title" to "Consistency Matrix (Last 28 days)",
        "stats_best_day" to "Peak Day",
        "stats_avg_daily" to "Daily Average",
        "stats_books_completed" to "Completed",
        "stats_in_progress" to "In Progress",
        "stats_quotes_saved" to "Saved Quotes",
        "stats_milestones_title" to "Badges & Milestones",
        "stats_badge_first_step" to "First Steps",
        "stats_badge_first_step_desc" to "Start your first book in Audire",
        "stats_badge_streak_3" to "Habit Formed",
        "stats_badge_streak_3_desc" to "Reach a 3-day reading streak",
        "stats_badge_streak_7" to "Unstoppable Fire",
        "stats_badge_streak_7_desc" to "Maintain a 7-day consecutive streak",
        "stats_badge_hours_5" to "Knowledge Marathon",
        "stats_badge_hours_5_desc" to "Exceed 5 hours of total reading/listening",
        "stats_badge_collector" to "Quote Collector",
        "stats_badge_collector_desc" to "Save 3 or more memorable quotes",
        "stats_badge_master" to "Audire Grandmaster",
        "stats_badge_master_desc" to "Reach the supreme rank with over 15 hours",
        // Achievement categories
        "achievements_all" to "All",
        "achievements_streaks" to "Streaks",
        "achievements_time" to "Time",
        "achievements_library" to "Library",
        "achievements_quotes" to "Quotes",
        "achievements_habits" to "Habits",
        "achievements_mastery" to "Mastery",
        "achievements_unlocked_count" to "Unlocked",
        // Reader Dock and Configuration Sheets
        "dock_nav" to "Pages",
        "dock_appearance" to "Appearance",
        "dock_scroll" to "Auto-Scroll",
        "dock_quotes" to "Quotes",
        "dock_voice" to "Narrator",
        "dock_pages_title" to "Page Navigation",
        "dock_appearance_title" to "Appearance Settings",
        "dock_scroll_title" to "Continuous Auto-Scroll",
        "dock_quotes_title" to "Book Quotes & Notes",
        "dock_voice_title" to "Voice Narration (TTS)",
        "dock_text_mode" to "Text Extraction Mode",
        "dock_visual_mode" to "Original Sheet Mode",
        "dock_inverted_night" to "Inverted Night Mode",
        "dock_inverted_night_desc" to "Inverts colors in PDFs and manga for eye comfort",
        "dock_font_size" to "Font Size",
        "dock_reading_theme" to "Reading Theme",
        "dock_add_quote_hint" to "Write or paste a highlighted phrase from this page...",
        "dock_save_quote" to "Save Quote",
        "dock_jump_page" to "Jump to Page",
        "dock_current_page" to "Current Page",
        // New strings for Modernized Settings
        "settings_subtitle" to "Fine-tune your listening and visual experience",
        "settings_cat_storage" to "Storage & Library",
        "settings_cat_appearance" to "Appearance & Theme",
        "settings_cat_playback" to "Playback & Voice Engine",
        "settings_cat_data" to "Backup & Diagnostics",
        "settings_cat_danger" to "Maintenance & Critical Zone",
        "settings_rescan_btn" to "Scan Files Now",
        "settings_rescan_desc" to "Index detected audiobooks, epubs and pdfs"
    )
}
